import type { Metadata } from "next";
import {  Outfit } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";

const outFit = Outfit({
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "TeleMedicine",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={outFit.className}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
